package com.github.wangchenning.springbootelaticjob.model;

import java.math.BigDecimal;
import java.util.Date;

public class TmailOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.id
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.order_status
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.money
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.create_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.create_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.update_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tmail_order.update_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.id
     *
     * @return the value of tmail_order.id
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.id
     *
     * @param id the value for tmail_order.id
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.order_status
     *
     * @return the value of tmail_order.order_status
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.order_status
     *
     * @param orderStatus the value for tmail_order.order_status
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.money
     *
     * @return the value of tmail_order.money
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.money
     *
     * @param money the value for tmail_order.money
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.create_user
     *
     * @return the value of tmail_order.create_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.create_user
     *
     * @param createUser the value for tmail_order.create_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.create_time
     *
     * @return the value of tmail_order.create_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.create_time
     *
     * @param createTime the value for tmail_order.create_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.update_user
     *
     * @return the value of tmail_order.update_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.update_user
     *
     * @param updateUser the value for tmail_order.update_user
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tmail_order.update_time
     *
     * @return the value of tmail_order.update_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tmail_order.update_time
     *
     * @param updateTime the value for tmail_order.update_time
     *
     * @mbg.generated Tue Jun 18 17:45:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}